---
# Default variables for bootstrap-libvirt role

# Image configuration
libvirt_fedora_version: "43"
libvirt_fedora_cloud_image_url: >-
  https://download.fedoraproject.org/pub/fedora/linux/releases/
  {{ libvirt_fedora_version }}/Cloud/x86_64/images/
  Fedora-Cloud-Base-Generic.x86_64-{{ libvirt_fedora_version }}-1.1.qcow2
libvirt_image_dir: "/var/lib/libvirt/images"
libvirt_base_image_name: "fedora-{{ libvirt_fedora_version }}-cloud-base.qcow2"
libvirt_min_disk_space_gb: 30

# SSH key configuration (should be set by bootstrap_workstation role)
libvirt_ssh_key_path: "{{ ansible_env.HOME }}/.ssh/id_fedora"

# VM configuration
libvirt_vms:
  - name: labhost1
    hostname: labhost1.local
    ip: 192.168.122.151
    mac: "52:54:00:00:00:01"
    memory: 2048
    vcpus: 2
    disk_size: 20
    graphics: "spice,listen=127.0.0.1"
  - name: labhost2
    hostname: labhost2.local
    ip: 192.168.122.152
    mac: "52:54:00:00:00:02"
    memory: 2048
    vcpus: 2
    disk_size: 20
    graphics: "spice,listen=127.0.0.1"
  - name: labhost3
    hostname: labhost3.local
    ip: 192.168.122.153
    mac: "52:54:00:00:00:03"
    memory: 2048
    vcpus: 2
    disk_size: 20
    graphics: "spice,listen=127.0.0.1"

# Cloud-init user configuration
libvirt_cloud_user: "cloud-user"
libvirt_ansible_user: "ansible"

# Libvirt network configuration
libvirt_network: "default"
libvirt_iso_network: "iso"
libvirt_iso_network_subnet: "10.10.5.0/24"
libvirt_iso_network_bridge: "virbr-iso"
